services:

  selenium-hub:
    image: selenium/hub:4.41.0-20260222
    container_name: selenium-hub
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4444/status || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20


  chrome:
    image: selenium/node-chrome:4.41.0-20260222
    container_name: selenium-chrome
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1


  edge:
    image: selenium/node-edge:4.41.0-20260222
    container_name: selenium-edge
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1


  firefox:
    image: selenium/node-firefox:4.41.0-20260222
    container_name: selenium-firefox
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1